// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqshlqyoqrniohlegvwc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxc2hscXlvcXJuaW9obGVndndjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNjc3NDgsImV4cCI6MjA2Mzc0Mzc0OH0.fdnXIIBT-E41e0b5VqUgfFD1Lb1e4HDpObB-UIRJsS0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);